name: Continuous Deployment

on:
  push:
    branches:
      - 5-KleinePipelineBasteln

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ich laufe nur auf ci-testing ğŸš€
        run: echo "Dieser Workflow lÃ¤uft nur, wenn auf 5-KleinePipelineBasteln gepusht wird."